apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadmfqx9191-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadmfqx9191-tenant-component
    app.kubernetes.io/part-of: loadmfqx9191-tenant-app
  name: loadmfqx9191-tenant-component
  namespace: loadmfqx9191-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: loadmfqx9191-tenant-component
    weight: null
status: {}
